FROM ubuntu:latest

SHELL [ "/bin/bash", "-c" ]

RUN apt update && apt upgrade -y
RUN apt-get update && apt-get upgrade -y

RUN apt install -y sudo git curl locales
RUN apt-get install -y language-pack-ja-base language-pack-ja fonts-noto-cjk fcitx-mozc

ENV GTK_IM_MODULE xim
ENV QT_IM_MODULE fcitx
ENV XMODIFIERS @im=fcitx
ENV DefalutIMModule=fcitx

RUN locale-gen ja_JP.UTF-8  
ENV LANG=ja_JP.UTF-8
ENV LC_ALL=ja_JP.UTF-8

ENV TZ Asia/Tokyo