version: '3.9'
services:
  python:
    build: 
      context: ubuntu
      dockerfile: ./Dockerfile.python3.9.18
      # args:
      #   - IMAGE_TAG=debian:latest
    image: python3.9.18
    container_name: pythonenv
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw