version: '3.9'
services:
  python:
    build: 
      context: .
      dockerfile: Dockerfile
      # args:
      #   - IMAGE_TAG=debian:latest
    image: python
    container_name: pythonenv
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw