FROM ubuntu:latest

SHELL [ "/bin/bash", "-c" ]

RUN apt update && apt upgrade -y
RUN apt-get update && apt-get upgrade -y

RUN apt install -y sudo git curl locales vim
# RUN apt-get install -y language-pack-ja-base language-pack-ja fonts-noto-cjk fcitx-mozc

# ENV GTK_IM_MODULE xim
# ENV QT_IM_MODULE fcitx
# ENV XMODIFIERS @im=fcitx
# ENV DefalutIMModule=fcitx

# RUN locale-gen ja_JP.UTF-8  
# ENV LANG=ja_JP.UTF-8
# ENV LC_ALL=ja_JP.UTF-8

# ENV TZ Asia/Tokyo

RUN bash <(curl -sSL https://raw.githubusercontent.com/skrjtech/Archives/main/Installer/python.sh) 3.10.13
RUN bash <(curl -sSL https://raw.githubusercontent.com/skrjtech/Archives/main/Installer/pycharm.sh) 2023.2.1

CMD [ "/bin/bash" ]